[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "UbuntuMono Nerd Font Mono"
style = "Regular"

[window]
#decorations = "None"
startup_mode = "Maximized"
dynamic_title = false
option_as_alt = "OnlyLeft"
#opacity = 0.90

[window.padding]
x = 0
y = 0

[general]
import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]
